### ISSUE TITLE
Robottelo setup on Python 3.12

### ISSUE THREAD

**Issue by ogajduse** [SatelliteQE/robottelo#11787]
## This is a tracking issue for robottelo setup on Python 3.12
Release date for 3.12 is October 2nd 2023.

### Blocking issues

- [ ] __ssh2-python fails to build on 3.12__: they will add 3.12 setup once 3.12 is released. Depends on https://github.com/ParallelSSH/ssh2-python/issues/193
- [x] __cryptography does not install on 3.12__: `AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`
- [ ] unittest deprecations breaking robottelo unit tests - https://docs.python.org/3/whatsnew/3.12.html#id3

**Comment by Gauravtalreja1** [comment]
I think cryptography issue won't be blocking us anymore with 3.12 
```
(.robottelo312) ➜  robottelo git:(master) ✗ pip install cryptography
Collecting cryptography
  Obtaining dependency information for cryptography from https://files.pythonhosted.org/packages/06/5d/f992c40471b60b762dca2b118c0a7837e446bea917f2be54b8f49802fe5e/cryptography-41.0.4-cp37-abi3-macosx_10_12_universal2.whl.metadata
  Using cached cryptography-41.0.4-cp37-abi3-macosx_10_12_universal2.whl.metadata (5.2 kB)
Collecting cffi>=1.12 (from cryptography)
  Obtaining dependency information for cffi>=1.12 from https://files.pythonhosted.org/packages/b4/f6/b28d2bfb5fca9e8f9afc9d05eae245bed9f6ba5c2897fefee7a9abeaf091/cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl.metadata
  Using cached cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using cached cryptography-41.0.4-cp37-abi3-macosx_10_12_universal2.whl (5.3 MB)
Using cached cffi-1.16.0-cp312-cp312-macosx_11_0_arm64.whl (177 kB)
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.16.0 cryptography-41.0.4 pycparser-2.21
```
