### ISSUE TITLE
API operating system failure

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/robottelo#3067]
tests.foreman.api.test_media.MediaTestCase.test_positive_create_with_operating_system (from nosetests)
'OperatingSystem' object has no attribute 'media'

This failure is introduced by https://github.com/SatelliteQE/nailgun/pull/243
