### PR TITLE
Update os media to medium to reflect nailgun update

### LINKED ISSUE #3067: API operating system failure
tests.foreman.api.test_media.MediaTestCase.test_positive_create_with_operating_system (from nosetests)
'OperatingSystem' object has no attribute 'media'

This failure is introduced by https://github.com/SatelliteQE/nailgun/pull/243

### PR DESCRIPTION
**Pull request by sthirugn**
Closed #3067

### CODE REVIEW

**Comment by sthirugn** [comment]
```
# nosetests tests/foreman/api/test_media.py:MediaTestCase.test_positive_create_with_operating_system
.
----------------------------------------------------------------------
Ran 1 test in 3.189s

OK
```

**Comment by oshtaier** [comment]
Thanks @sthirugn for that fix
ACK

**Comment by abalakh** [comment]
ACK
