### PR TITLE
Fix test_remoteexecution failure due to ssh.command wrong output format

### PR DESCRIPTION
**Pull request by rochacbruno**
The following failure in automation:

```console
Test Result : tests.foreman.ui.test_remoteexecution
@tier2
    def test_positive_run_default_job_template(self):
        """Run a job template against a single host
...
>           key_type, key_string, comment = key.split()
E           AttributeError: 'list' object has no attribute 'split'
```

happening because a change introduced in https://github.com/SatelliteQE/robottelo/commit/5b91121dcc38f218fcc977469a009e38db6c98b4

Rational:

Our SSHCommandResult tries to transform **csv** outputs into a **list** striping out **rails** specific messages, but that should be done only for hammer commands with **csv** output defined, currently most tests pass None as output format but expects to be hammer **csv**.

So I added a new out_format **plain** which skips the transformation of the command output in to a list returning only the pure plain text stdout.

Now ssh key upload works again using the plain text output.

Added some `# pragma: no cover` on places where we are not going to unit-test (mostly related to file uploads)

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK

**Comment by renzon** [comment]
ACK
