### PR TITLE
[6.2.z] implemented discovered host tests from UI with helper funtions and fixed existing tests

### PR DESCRIPTION
**Pull request by sghai**
Cherry-picked the commit from master that includes some fixes around discovery tests and new tests implemented around discovered host. There were some comments given after PR got merged.

I'll raise another PR later to fix those comments but would like to have these changes merged in 6.2.z branch first.

### CODE REVIEW

**Comment by sghai** [comment]
@abalakh : hey.. I'm willing to provide test results but looks like I won't be. Recently I installed Fedora24 and installed latest firefox50 which actually works perfectly with selenium==2.53.6 when running against sat6.3 version.

However, when I run same test against sat6.2 using same FF50 & selenium==2.53.6, I end up with webdriver exception:

```console
tests/foreman/ui/test_discoveredhost.py:680: in test_positive_update_default_org
    with Session(self.browser) as session:
robottelo/ui/session.py:31: in __enter__
    self.login()
robottelo/ui/session.py:40: in login
    self._login.login(self.user, self.password)
robottelo/ui/login.py:21: in login
    self.click(common_locators['submit'])
robottelo/ui/base.py:646: in click
    self.scroll_into_view(element)
robottelo/ui/base.py:450: in scroll_into_view
    element,
/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:465: in execute_script
    'args': converted_args})['value']
/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    self.error_handler.check_response(response)
```
```
E       WebDriverException: Message: arguments[0].scrollIntoView is not a function
```

Any idea or suggestion how can we get rid of this ?

**Comment by abalakh** [comment]
@sghai answered in IRC. The solution is to run `make pyc-clean` after each switch between sat versions.

**Comment by sghai** [comment]
@abalakh thank you for the tip. Solution works.

**Comment by sghai** [comment]
Test results:

```console

 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_add_fact_column
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_add_fact_column <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 154.13 seconds ======================================================


 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_update_default_org
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_update_default_org <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 260.97 seconds ======================================================



robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_reboot
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_reboot <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 236.27 seconds ======================================================



robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_delete_multiple
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete_multiple <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 286.06 seconds ======================================================


 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_delete_from_facts
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete_from_facts <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 188.78 seconds ======================================================



robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_delete
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_delete <- robottelo/decorators/__init__.py PASSED


robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_custom_facts_discovery
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_custom_facts_discovery <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
====================================================== 1 passed, 41 deselected in 93.61 seconds =====================================================


 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_pxe_multi_nic_unattended
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_pxe_multi_nic_unattended <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 148.90 seconds ======================================================


robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_pxe_less_multi_nic_with_dhcp_unattended
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_pxe_less_multi_nic_with_dhcp_unattended <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
====================================================== 1 passed, 41 deselected in 92.71 seconds ======================================================

 robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_pxe_less_with_dhcp_unattended
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_pxe_less_with_dhcp_unattended <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
====================================================== 1 passed, 41 deselected in 83.12 seconds ======================================================


robottelo]$ py.test -v tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase -k test_positive_pxe_based_discovery
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /home/sghai/QE/robottelo, inifile: 
collected 42 items 

tests/foreman/ui/test_discoveredhost.py::DiscoveryTestCase::test_positive_pxe_based_discovery <- robottelo/decorators/__init__.py PASSED

================================================================ 41 tests deselected =================================================================
===================================================== 1 passed, 41 deselected in 139.67 seconds ======================================================
```

**Comment by sghai** [comment]
@abalakh @oshtaier : Guys...  I ran all tests one after another and fixed the place where we need to use old notation of strategy, value around locators. I think now this PR is good to merge.

**Comment by renzon** [comment]
ACK
